language: julia

os:
  - linux
  - windows
  - osx

julia:
  - 1.4
  - 1.5

notifications:
  email: false
  
after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("QTBase")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
